// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import { defineChain } from 'viem'
import { chainConfig } from 'viem/op-stack'

const sepoliaSourceId = 11_155_111
export const riseSepolia = defineChain({
  ...chainConfig,
  id: 11155931,
  name: 'Rise Sepolia',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://staging.riselabs.xyz'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.staging.riselabs.xyz',
    },
  },
  sourceId: sepoliaSourceId,
  testnet: true,
  contracts: {
    ...chainConfig.contracts,
    // DisputeGameFactoryProxy
    disputeGameFactory: {
      [sepoliaSourceId]: {
        address: '0xb41b992bd93acb561f5fa38ddd9115371891ad36',
      },
    },
    // L2OutputOracleProxy
    l2OutputOracle: {
      [sepoliaSourceId]: {
        address: '0x0000000000000000000000000000000000000000',
      },
    },
    // multicall3: {
    //   address: '0xca11bde05977b3631167028862be2a173976ca11',
    //   blockCreated: 1620204,
    // },
    // OptimismPortalProxy
    portal: {
      [sepoliaSourceId]: {
        address: '0x3da939b2668dbcaddf926809a00c8737a5c15b13',
      },
    },
    // L1StandardBridgeProxy
    l1StandardBridge: {
      [sepoliaSourceId]: {
        address: '0x4e32d8d3be0dcee8398859cf513ebcb8f4d490cc',
      },
    },
  },
})

export const orderlyNetwork = defineChain({
  ...chainConfig,
  id: 291,
  name: 'Orderly Network',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.orderly.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.orderly.network',
    },
  },
  sourceId: 1,
})

export const lyra = defineChain({
  ...chainConfig,
  id: 957,
  name: 'Lyra',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.lyra.finance'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.lyra.finance',
    },
  },
  sourceId: 1,
})

export const mode = defineChain({
  ...chainConfig,
  id: 34443,
  name: 'Mode',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.mode.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.mode.network',
    },
  },
  sourceId: 1,
})
