// DO NOT MODIFY THIS FILE IS AUTOGENERATED
import { defineChain } from 'viem'
import { chainConfig } from 'viem/op-stack'

const sepoliaSourceId = 11_155_111
export const riseSepolia = defineChain({
  ...chainConfig,
  id: 11155931,
  name: 'Rise Sepolia',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://testnet.riselabs.xyz'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://testnet-explorer.riselabs.xyz',
    },
  },
  sourceId: sepoliaSourceId,
  testnet: true,
  contracts: {
    ...chainConfig.contracts,
    // DisputeGameFactoryProxy
    disputeGameFactory: {
      [sepoliaSourceId]: {
        address: '0x3d376Ef7f4475EB236E5246EDf39b36B908f56d5',
      },
    },
    // L2OutputOracleProxy
    l2OutputOracle: {
      [sepoliaSourceId]: {
        address: '0x5001918fCEDCa9D321D35E04E2f59f163658BfdC',
      },
    },
    // multicall3: {
    //   address: '0xca11bde05977b3631167028862be2a173976ca11',
    //   blockCreated: 1620204,
    // },
    // OptimismPortalProxy
    portal: {
      [sepoliaSourceId]: {
        address: '0x7b5586dd10B7a57F35bC6F68E99Aba0c0D09a929',
      },
    },
    // L1StandardBridgeProxy
    l1StandardBridge: {
      [sepoliaSourceId]: {
        address: '0xB525dF7E8101506D333Dc924Ef802789820E3cEA',
      },
    },
  },
})

export const orderlyNetwork = defineChain({
  ...chainConfig,
  id: 291,
  name: 'Orderly Network',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.orderly.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.orderly.network',
    },
  },
  sourceId: 1,
})

export const lyra = defineChain({
  ...chainConfig,
  id: 957,
  name: 'Lyra',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.lyra.finance'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.lyra.finance',
    },
  },
  sourceId: 1,
})

export const mode = defineChain({
  ...chainConfig,
  id: 34443,
  name: 'Mode',
  nativeCurrency: {
    decimals: 18,
    name: 'Ether',
    symbol: 'ETH',
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.mode.network'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Blockscout',
      url: 'https://explorer.mode.network',
    },
  },
  sourceId: 1,
})
