name: Release Bridge UI App

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging-config

jobs:
  build-docker:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Authenticate with GCP
      - name: Authenticate with Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_ARTIFACT_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "sa-rise-github-actions@${{ secrets.GCP_ARTIFACT_PROJECT_ID }}.iam.gserviceaccount.com"

      # Configure Docker to use the GCP Artifact Registry
      - name: Configure Docker for GCP Artifact Registry
        run: |
          echo "Configuring Docker to authenticate with GCP Artifact Registry..."
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Config Docker Buildx
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_ARTIFACT_PROJECT_ID }}/risechain/bridge-ui
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=stag.latest

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.bridgeApp
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_WALLET_CONNECT_PROJECT_ID=${{ secrets.VITE_WALLET_CONNECT_PROJECT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      # Scan the Docker image with Trivy
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_ARTIFACT_PROJECT_ID }}/risechain/bridge-ui:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
